### ISSUE TITLE
Make Contigo load up correctly

### ISSUE THREAD

**Issue by djoveryde** [djoveryde/Contigo#7]
Next challenge is making the loader load up successfully. Right now it throws the following:

Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25)
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 4 more

**Comment by CDAGaming** [comment]
@SantaGitHub knows the solution to this as its caused from the update to Jopt

**Comment by CDAGaming** [comment]
Hm, i seem to be getting another error

**Comment by CDAGaming** [comment]
![2017-08-28 4](https://user-images.githubusercontent.com/16328918/29794676-9ea2f482-8c0e-11e7-9af6-aaa2bcbd98e6.png)

**Comment by djoveryde** [comment]
Did you initially install the Forge server installer?

**Comment by CDAGaming** [comment]
*facepalm* Thought it would auto do that

**Comment by CDAGaming** [comment]
Ladies and Gentelmen, the biggest forge noob 👍

**Comment by djoveryde** [comment]
lol, sadly not, not sure if thats to do with EULA on the minecrafts server jar or something.

**Comment by CDAGaming** [comment]
@djoveryde Also, are you going to add Travis back (I would but i do not have the perms to do so :P )

**Comment by djoveryde** [comment]
Never dealt with travis, how do i do this?

**Comment by CDAGaming** [comment]
Well it should be as easy as going onto Travis and adding this repo to it
Once you do that, then just have it trigger a custom build for an initial build

**Comment by CDAGaming** [comment]
For JOpt issue, it should be fixed in the update (Which Santa might have to properly configure)

**Comment by djoveryde** [comment]
Yup, I've added everything to the folders so should work although even with special source and joptsimple being set to the correct set it's still not loading. Pondering if I need to add those to the ftp as well or wether we just add a library zip with those jars in it for people to grab along with a compiled version.

**Comment by CDAGaming** [comment]
Well, it mostly is (Because its building now)

Perhaps its something in that dependency screwing up, which @SantaGitHub did say it was successfully running, but with some changes...

**Comment by SantaGitHub** [comment]
Прошу прощения за русский язык.
Скачайте libraries.zip с 58 версии(Thermos). 

**1.** Затем скачайте с интернета **_SpecialSource-1.7.4_** и **_Jopt-simple 5.0.1_** . 
**2.** Распакуйте **_libraries_** рядом с вашим **_Jar_** файлом. 
**3.** В папке **_libraries_** замените **_SpecialSource_** и **_Jopt-simple_** на новые версии, а старые удалите. 
**4.** Запускайте сервер.

**Comment by SantaGitHub** [comment]
@djoveryde Please add this files to repo - pw.prok:Damask:0.1.2.
```
Could not resolve all dependencies for configuration ':bootstrap'.
> Could not resolve pw.prok:Damask:0.1.2.
  Required by:
      cyberdynecc:Thermos:1.7.10-1614.UNOFFICIAL > pw.prok:KBootstrap:0.2.0
   > Could not resolve pw.prok:Damask:0.1.2.
      > Could not get resource 'https://djoveryde.000webhostapp.com/kcauldron/files/pw/prok/Damask/0.1.2/Damask-0.1.2.pom'.
         > Could not GET 'https://djoveryde.000webhostapp.com/kcauldron/files/pw/prok/Damask/0.1.2/Damask-0.1.2.pom'.
            > The target server failed to respond
```

**Comment by djoveryde** [comment]
Done, how I missed that guy I have no idea. Let me know if there's any more

**Comment by SantaGitHub** [comment]
To build a server + libraries, you must enter ./gradlew packageBundle.

**Comment by djoveryde** [comment]
New build fail issue 

What went wrong:
Execution failed for task ':Cauldron:compileJava'.
> Could not find tools.jar

Not sure where to even find tools.jar file

**Comment by djoveryde** [comment]
While packaging the bundle for some unknown reason it switches to the local drive to find the launchwrapper jar file.. Had to manually add that in

Server directory: D:\Users\djove\Desktop\New folder\Contigo\build\bundle
Downloading net.minecraft:launchwrapper:1.12... java.io.FileNotFoundException: D:\Users\djove\Desktop\New folder\Contigo\build\bundle\bin\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar (The system cannot find the file specified)

**Comment by djoveryde** [comment]
I've made a release for this version along with downloadable library zip

**Comment by CDAGaming** [comment]
Yea, had that come up in my travis as well
Then again you need to set your repo, which ill commit now @djoveryde

**Comment by djoveryde** [comment]
Ok cheers, at least were getting there one bug at a time 👍

**Comment by SantaGitHub** [comment]
Потому что в KBootstrap прописан репо от Prok.

**Comment by CDAGaming** [comment]
It will however still error with the abstractmethod, bc it is using Gradle 3.2.1
The version needs to be set to 2.8 to build with success with travis

**Comment by djoveryde** [comment]
**bangs head against the table** why did I forget to change the travis repo... stupid me lol

**Comment by djoveryde** [comment]
@SantaGitHub  so if I change "https://prok.pw/gitlab/Prototik/KBootstrap.git" in the kbootstrap.pom file to "https://github.com/djoveryde/Contigo.git"?

**Comment by djoveryde** [comment]
Tried finding any trace of the kbootstrap git but seems no one backed it up :-/

**Comment by djoveryde** [comment]
@CDAGaming Do you reckon we would be able to safely remove kbootstrap from the dependencies?

**Comment by CDAGaming** [comment]
Not sure, working on #8 at this time, extending from previous attempt at it by AscII

**Comment by djoveryde** [comment]
I'll add a new repo for 1.11.2 contigo, at least that way we have a baseline 1.7.10 and then an updated choice to work on

**Comment by CDAGaming** [comment]
Yea, i got the basics just let me finish up submodules

**Comment by SantaGitHub** [comment]
Можно пересобрать kbootstrap и указать в нём наши репозитории. Так будет лучше

**Comment by CDAGaming** [comment]
Yea that can be done, KBootstrao was also found in SourceForge, so it should just need to be moved to new repo

**Comment by djoveryde** [comment]
the actual bootstrap file is already on the repo however when it looks for both kbootstrap-0.3.2.jar and Damask-0.1.2.jar, it only seems to want to find them locally. Any ideas where we can change this would be to so it looks on the repo instead?
Server directory: /home/travis/build/djoveryde/Contigo/build/bundle
Downloading pw.prok:KBootstrap:0.3.2... java.io.FileNotFoundException: /home/travis/build/djoveryde/Contigo/build/bundle/bin/pw/prok/KBootstrap/0.3.2/KBootstrap-0.3.2.jar (No such file or directory)

**Comment by CDAGaming** [comment]
Also I'm currently in progress of making the 1.12.1/Latest Port(Submodules are 
Proofed for your repos as they use a different linkage

I'll add you as contributor in a bit to help on it(Partially done, can work more on it later)

**Comment by djoveryde** [comment]
ok so i've managed to convert the jar file although its never gonna recompile again without creating all the build setups.
https://github.com/djoveryde/KBootstrap

The actual location its looking is in the pw/prok/bootstrap/Main.java which sits at "    this.serverDir = new Option("d", "serverDir", true, "Server root directory");"

If we could add a way so it overwrites the serverdir and enforces it to change to the repo that could work?

**Comment by djoveryde** [comment]
@CDAGaming @SantaGitHub Removed the other repo. Hopefully we can make this stable and then move onto 1.12 or 1.11.2

**Comment by CDAGaming** [comment]
Unfortunately due to the Submodule issue, we may not be able to do 1.11.2(Unless your willing to either have users download or have Bukkit and forge Submodules in repo at their correct commits/branches. I'd suggest, because of this, to work on 1.12.1 after this

**Comment by CDAGaming** [comment]
So far, I have the initial work done on it(Besides updating the json files)

**Comment by SantaGitHub** [comment]
Found an error solution with packageBundle.
We need to open all the .pom files on our repository and change the reference to our repository

**Comment by djoveryde** [comment]
Pretty sure only the kbootstraps pom file has references to the old repo. The others purely mention apache.

**Comment by SantaGitHub** [comment]
Надо все файлы, которые находятся у тебя на репозитории проверить .pom файлы на наличие ссылки на новый репозиторий
